# Importando o pandas

In [ ]:
#Esse comando funciona dentro do google colab
#!pip install --upgrade pandas

In [6]:
#importando o pandas
import pandas as pd

In [16]:
#Configurando para que os floats tenham duas cadas decimais
pd.set_option('display.float_format', '{:.2f}'.format)

# Dados de exemplo

In [2]:
#Criando um dicionário
dados = {
   'Nome': ['Alice', 'Bruno','Carlos','Daniela'],
   'Idade':[25, 20, 22, 27],
   'Salário':[3000, 4500, 2500, 5200]
}
print(dados)

{'Nome': ['Alice', 'Bruno', 'Carlos', 'Daniela'], 'Idade': [25, 20, 22, 27], 'Salário': [3000, 4500, 2500, 5200]}

In [7]:
#Convertendo para dataFrame
df = pd.DataFrame(dados)
df
#Dentro de um arquivo .py
#print(df)

      Nome  Idade  Salário
0    Alice     25     3000
1    Bruno     20     4500
2   Carlos     22     2500
3  Daniela     27     5200

In [8]:
#df = pd.read_csv('https://fit.faccat.br/~rh/datasets/a5/streaming_preferences.csv')
#df = pd.read_csv('sample_data/streaming_preferences.csv')
df = pd.read_csv('dataset/streaming_preferences.csv')

#Verificando a quatidade de linhas e colunas do dataframe

In [10]:
#Mostra a quantidade linhas e colunas do dataset
df.shape

(5000, 12)

# Olhando as n primeiras do dataframe

In [14]:
df.head(10)

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
0,U1000,34,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74
1,U1001,24,Germany,Deezer,Country,86,388,Ed Sheeran,Premium,Night,12.06,69.25
2,U1002,49,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38
3,U1003,55,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51
4,U1004,13,Germany,Amazon Music,Reggae,30,328,Adele,Free,Night,30.68,43.41
5,U1005,25,South Korea,Spotify,EDM,536,243,The Weeknd,Premium,Afternoon,70.26,27.79
6,U1006,49,Australia,Tidal,Country,547,70,Billie Eilish,Free,Night,11.92,37.75
7,U1007,32,UK,Amazon Music,Classical,98,448,Dua Lipa,Premium,Afternoon,29.48,18.80
8,U1008,25,Germany,Tidal,Metal,526,27,BTS,Premium,Morning,85.70,42.38
9,U1009,37,Brazil,Spotify,Reggae,514,299,Billie Eilish,Premium,Morning,53.39,46.89

# Olhando as n linhas finais do dataframe

In [15]:
df.tail(10)

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
4990,U5990,32,USA,Amazon Music,EDM,511,136,Bad Bunny,Free,Night,39.58,12.02
4991,U5991,27,South Korea,Spotify,R&B,51,166,Post Malone,Premium,Night,12.41,73.82
4992,U5992,46,UK,Apple Music,Hip-Hop,291,64,The Weeknd,Premium,Afternoon,36.62,78.22
4993,U5993,19,Germany,Tidal,Jazz,344,409,Taylor Swift,Premium,Afternoon,61.33,43.26
4994,U5994,55,Australia,Amazon Music,Classical,222,444,Dua Lipa,Premium,Night,56.49,44.17
4995,U5995,60,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36
4996,U5996,38,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,17.08,58.23
4997,U5997,27,Brazil,Amazon Music,Metal,568,277,Taylor Swift,Premium,Night,69.39,51.71
4998,U5998,58,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53
4999,U5999,30,South Korea,YouTube,Rock,451,145,Adele,Premium,Night,15.45,79.46

# Mostrando informações do dataframe

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   User_ID                                   5000 non-null   object
 1   Age                                       5000 non-null   int64
 2   Country                                   5000 non-null   object
 3   Streaming Platform                        5000 non-null   object
 4   Top Genre                                 5000 non-null   object
 5   Minutes Streamed Per Day                  5000 non-null   int64
 6   Number of Songs Liked                     5000 non-null   int64
 7   Most Played Artist                        5000 non-null   object
 8   Subscription Type                         5000 non-null   object
 9   Listening Time (Morning/Afternoon/Night)  5000 non-null   object
 10  Discover Weekly Engagement (%)            5000 non-null   float64
 11  Repeat Song Rate (%)                      5000 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 468.9+ KB

# Monstrando a descrição dos dados

In [19]:
df.describe(include='all')

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
count,5000,5000.00,5000,5000,5000,5000.00,5000.00,5000,5000,5000,5000.00,5000.00
unique,5000,NaN,10,6,10,NaN,NaN,10,2,3,NaN,NaN
top,U1000,NaN,Australia,Amazon Music,Reggae,NaN,NaN,Bad Bunny,Premium,Night,NaN,NaN
freq,1,NaN,526,861,532,NaN,NaN,528,2526,1745,NaN,NaN
mean,NaN,36.66,NaN,NaN,NaN,309.24,253.52,NaN,NaN,NaN,50.30,42.39
std,NaN,13.76,NaN,NaN,NaN,172.03,146.37,NaN,NaN,NaN,23.17,21.44
min,NaN,13.00,NaN,NaN,NaN,10.00,1.00,NaN,NaN,NaN,10.02,5.00
25%,NaN,25.00,NaN,NaN,NaN,161.00,126.00,NaN,NaN,NaN,30.15,24.20
50%,NaN,37.00,NaN,NaN,NaN,316.00,254.00,NaN,NaN,NaN,50.42,41.96
75%,NaN,49.00,NaN,NaN,NaN,457.25,382.00,NaN,NaN,NaN,70.34,60.74
max,NaN,60.00,NaN,NaN,NaN,600.00,500.00,NaN,NaN,NaN,89.99,79.99

# Contando os dados nulos

In [21]:
df.isnull().sum()

User_ID                                     0
Age                                         0
Country                                     0
Streaming Platform                          0
Top Genre                                   0
Minutes Streamed Per Day                    0
Number of Songs Liked                       0
Most Played Artist                          0
Subscription Type                           0
Listening Time (Morning/Afternoon/Night)    0
Discover Weekly Engagement (%)              0
Repeat Song Rate (%)                        0
dtype: int64

#Contagem de valores únicos de cada coluna

In [22]:
df.nunique()

User_ID                                     5000
Age                                           48
Country                                       10
Streaming Platform                             6
Top Genre                                     10
Minutes Streamed Per Day                     591
Number of Songs Liked                        500
Most Played Artist                            10
Subscription Type                              2
Listening Time (Morning/Afternoon/Night)       3
Discover Weekly Engagement (%)              3687
Repeat Song Rate (%)                        3687
dtype: int64

In [23]:
df['Country'].unique()

array(['Japan', 'Germany', 'Australia', 'South Korea', 'UK', 'Brazil',
       'Canada', 'India', 'USA', 'France'], dtype=object)

In [24]:
for coluna in df.columns:
    print(f'{coluna} {df[coluna].unique()}')
#df['Country'].unique()

User_ID ['U1000' 'U1001' 'U1002' ... 'U5997' 'U5998' 'U5999']
Age [34 24 49 55 13 25 32 37 40 43 46 57 23 33 19 16 17 39 29 42 35 53 27 51
 47 58 38 26 50 56 54 14 48 20 30 18 60 52 59 22 36 31 21 41 45 28 44 15]
Country ['Japan' 'Germany' 'Australia' 'South Korea' 'UK' 'Brazil' 'Canada'
 'India' 'USA' 'France']
Streaming Platform ['Tidal' 'Deezer' 'YouTube' 'Amazon Music' 'Spotify' 'Apple Music']
Top Genre ['Reggae' 'Country' 'Pop' 'EDM' 'Classical' 'Metal' 'Rock' 'Hip-Hop' 'R&B'
 'Jazz']
Minutes Streamed Per Day [295  86 363 348  30 536 547  98 526 514 266 351 389 506 502 193 542  13
 383 147  58 450 445 218  87 537 203 267 151  60 201 564 140 187 332  99
 265 370 478 581  93 463  84 404 149 585 485 249 225 414 189  88  43 259
 202 429 282  67 587 262 372 229 316 334 580 538 394 228 570 342 530 251
 331 435 419 364  23 365 574 474 252 123  49 217 222  31 426 578 451 454
 283 136 311  11 379 327 131 476 144  74  76 473 539 318 199 531 234 386
  70 274 491 345 208 105  44 146 250 152 350 558  57 264 489 415 176 336
 567  50 121 535 513 135 284 240 296 221 546 366 490  54 169 220 595 592
  37 521 524 548 438 518 160 560 390 418 471 425 590 449 125 407 520 200
 317 549 352 126 119  62 100  10 134 551 369 376 116 180 226  51 406 459
 440 373 183 139 272 385 396 224 223  46  39 163 279 335 118 519 555 361
 194 143  35 557 465 233 563  36 493 588 597 236 481 219 600  77 255 299
 239 328  32 409 349 281 320  21 446 591  41 301 168 437  27 117 164 422
 289 312 559 475 397 268  83 504 242 525 292 157 207  47 565 484 405 287
  14 541 258 109 356 300 468  52 392 159 256 212 181 315 421 260 257 460
 263 375 174  29 533 271 573 391 184 319 545 313 452  56  55 534 108 444
 495 433 237  22 384 245 270 210 269 127 477 333 456 532  69 188 441 447
 410 323 572 402 112 129  18 338 360  24 393 388  33 171 494 516 357 496
 178 196 111 427 243 579 190 527  45 153 467 115  96 324  89  78 137  92
 293 453 431 377 382 186  16 458 197 368 479 156 343 544 309  82  65 253
 340 395 416 399 566 166  12 158  19 130  40 214  17 594 141 216 553 275
 230 101 424  73 523 307 439 442 314 261 503 367 145 448 593 273 177 486
 483  68 254  34 195 227 505 575 288 113 554 148 308 487 248 398 294 175
 469 529 359 472 355 420 241 322 103 354  75 498 400 192  95 381 114 326
 104 499 480 198 154  61  85 167 310 133 576  91  90 128 290 306 455 411
 247 583 329 302  25 457 170  15 522 339 232 432 110 277 122 408 470 464
 179 482 305  20  80  26 387 543 238 589 509 552 291 488 586  48 510 278
 235 443 428  72 501 231 106 417  53 344 173 276  66 191 165 401 577 412
 341 346 599 584 182 374 155 347 325  71 380 500 528 569 371 568 161 571
 462  38 517  97 162 142 358 430 213 206 362 413 138 353 466 286  79 215
 540  64 298 244 508 556 303 209 596 321 297 403 107 205 550  59 102  81
 124 120  94 185 512 132 246 330  28 434 515 461 280 172 204 304  42 598
 150 582 507 378 285 211 492 423 511 337 562 436 497  63 561]
Number of Songs Liked [138 388 368 349 328 243  70 448  27 299 462 108 432 215  11 499 423 468
 461 417  12 221 248 347 494 437 475 195  52 400 408 439 196  80  95   4
 300 454 434 264 463 117 464 110 306 342 178 214 393 374 315 490   8 225
 191 320 301 283  79 451 151 363  94  71 212 310 236 476 122 165 440 171
 259  64 419 272 129 222 207 153  67 354 339 170 150  87 101 102 486 282
 210 198 274 427  84 208 119 118 112  88 378 484 411 113 205 193 318 345
 291 133  97 415 226 166 183 344 247 465  85 287 489 130  25 321   3  17
 491 182 485 445 114  73 421 275 120 276 425 435  29 394  37  91 168 371
   9 256 140 389 392 496 162 160 200  93  33 385 460 443 353  31   1 379
 181  30 477 267 334 309 258 127 314 111 424 169 268 262 246 179 239 270
 277 479 271 294 414 217 381  15 337 228  92 396 251  45 380 115 232 154
 295  59  46 125 469   5 263  99 203 123 188 234  48 481 377 148 155 333
 480 428 103 107 348 364 384 375 131  50 433 143  44 237 280 201 312  35
  49  62  53 356 190 204 231 322 106 456 213 132 253  36 245 416 307 233
 493 351 482 141 452 472 249 293  20  56 431 184  41  78 238 399 471 298
 304 104 402 281 369 327  63 405  18 329 352  72  98 158 410  14  55 495
  39 367  65 175  10   2  75 331   7 429 255 418 124 286 240 128 216 497
 157  38 142   6 136  24  32 404  69 444 430 206 358 202 139 323 326 391
  16 412 137 473  61 395 261 218 174 105 149 189 109 219 343  26 292 177
 350 441 450 223  74 290 366 372 466 457 161 325  47 144 269 359 453  81
 229 311  22 192  58 426 296 285 187 235 336 488 116 340  42 163 303 409
  96 313 474 164 492 401 455 316 172 147 470 167 341 308 244  60 397  13
 302 365 373 376 173  83 265 459  68 446 438 185 305 332  90 186 289  34
 241 449  54 500 498 361 487 420 252 278 159 403  23 135 260  21 386 447
 370 483 279 126 145 387 413 121 478 257 273  76  19 436 297 100 407 317
 360  77  28 242 406 284 180 230 266 422 383  82 250  89 338  40 288 209
 382 220 335 194 324 152 355 458 146 227 346 357 254 199  43  51  86 176
 467  57 211 330  66 442 224 362 197 390 134 319 156 398]
Most Played Artist ['Adele' 'Ed Sheeran' 'Post Malone' 'Dua Lipa' 'The Weeknd'
 'Billie Eilish' 'BTS' 'Taylor Swift' 'Drake' 'Bad Bunny']
Subscription Type ['Free' 'Premium']
Listening Time (Morning/Afternoon/Night) ['Afternoon' 'Night' 'Morning']
Discover Weekly Engagement (%) [47.42 12.06 47.19 ... 49.23 17.08 15.45]
Repeat Song Rate (%) [16.74 69.25 67.38 ... 44.17 24.53 79.46]

# Selecionando dados

In [26]:
pais = df[['Country', 'Top Genre', 'Age']]
pais

          Country Top Genre  Age
0           Japan    Reggae   34
1         Germany   Country   24
2         Germany       Pop   49
3       Australia    Reggae   55
4         Germany    Reggae   13
...           ...       ...  ...
4995           UK   Country   60
4996    Australia   Hip-Hop   38
4997       Brazil     Metal   27
4998       Canada       EDM   58
4999  South Korea      Rock   30

[5000 rows x 3 columns]

In [27]:
#Obtendo o registro pelo índice
df.iloc[3]

User_ID                                         U1003
Age                                                55
Country                                     Australia
Streaming Platform                            YouTube
Top Genre                                      Reggae
Minutes Streamed Per Day                          348
Number of Songs Liked                             349
Most Played Artist                           Dua Lipa
Subscription Type                             Premium
Listening Time (Morning/Afternoon/Night)      Morning
Discover Weekly Engagement (%)                  31.27
Repeat Song Rate (%)                            76.51
Name: 3, dtype: object

In [37]:
# Obtendo um registro e uma coluna específica
print(df.loc[10,['Age','Streaming Platform']])
print(df.loc[10,'Age'])

Age                       40
Streaming Platform    Deezer
Name: 10, dtype: object
40

In [45]:
df[(df['Country']=='Brazil') & (df['Top Genre'] == 'Reggae') & (df['Subscription Type']=='Free')]

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
100,U1100,17,Brazil,YouTube,Reggae,379,486,Taylor Swift,Free,Night,57.31,34.10
603,U1603,27,Brazil,Spotify,Reggae,166,491,The Weeknd,Free,Morning,29.84,14.15
756,U1756,21,Brazil,Amazon Music,Reggae,529,486,BTS,Free,Night,43.19,66.15
890,U1890,45,Brazil,Tidal,Reggae,44,495,BTS,Free,Night,10.43,24.65
1006,U2006,43,Brazil,Tidal,Reggae,188,128,BTS,Free,Night,45.74,35.48
1679,U2679,57,Brazil,Amazon Music,Reggae,459,445,Taylor Swift,Free,Morning,89.67,49.44
1759,U2759,19,Brazil,Tidal,Reggae,130,217,Adele,Free,Morning,27.00,50.25
1857,U2857,49,Brazil,Amazon Music,Reggae,484,269,Drake,Free,Morning,77.92,59.63
2072,U3072,35,Brazil,YouTube,Reggae,267,378,Bad Bunny,Free,Afternoon,42.28,67.23
2109,U3109,59,Brazil,Spotify,Reggae,554,87,Post Malone,Free,Night,37.14,56.89
2228,U3228,24,Brazil,Tidal,Reggae,72,183,The Weeknd,Free,Afternoon,87.83,15.77
2282,U3282,36,Brazil,Spotify,Reggae,335,391,The Weeknd,Free,Afternoon,29.46,44.64
2824,U3824,21,Brazil,Spotify,Reggae,122,409,The Weeknd,Free,Afternoon,49.67,28.45
3128,U4128,59,Brazil,Amazon Music,Reggae,132,19,Dua Lipa,Free,Morning,54.44,27.66
3474,U4474,23,Brazil,Spotify,Reggae,58,122,The Weeknd,Free,Morning,37.19,29.83
3734,U4734,46,Brazil,Spotify,Reggae,211,318,Taylor Swift,Free,Night,38.57,72.94
4150,U5150,34,Brazil,Deezer,Reggae,574,69,Bad Bunny,Free,Night,50.98,49.50
4551,U5551,22,Brazil,YouTube,Reggae,351,433,Taylor Swift,Free,Morning,26.25,65.79
4846,U5846,42,Brazil,YouTube,Reggae,137,316,Billie Eilish,Free,Morning,49.53,11.08

In [46]:
df[(df['Country']=='Brazil') & (df['Age']>30)]

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
9,U1009,37,Brazil,Spotify,Reggae,514,299,Billie Eilish,Premium,Morning,53.39,46.89
11,U1011,43,Brazil,Spotify,Rock,351,108,Drake,Free,Afternoon,48.15,23.70
22,U1022,40,Brazil,Tidal,Jazz,445,221,Dua Lipa,Premium,Morning,80.53,78.27
23,U1023,42,Brazil,Amazon Music,Rock,547,248,Post Malone,Free,Night,26.03,8.42
25,U1025,53,Brazil,Apple Music,Reggae,87,347,Ed Sheeran,Premium,Afternoon,60.40,10.49
...,...,...,...,...,...,...,...,...,...,...,...,...
4924,U5924,31,Brazil,Tidal,Pop,545,479,Dua Lipa,Free,Afternoon,48.71,68.39
4938,U5938,34,Brazil,Tidal,Rock,435,44,Ed Sheeran,Premium,Morning,25.22,60.95
4947,U5947,35,Brazil,Amazon Music,Classical,171,480,Drake,Premium,Morning,66.12,32.21
4955,U5955,34,Brazil,Apple Music,Hip-Hop,163,108,Post Malone,Free,Morning,62.17,71.06
4983,U5983,45,Brazil,Tidal,Rock,469,485,Adele,Premium,Night,16.16,54.74

#Alterando dados

In [60]:
#Criando uma  nova coluna
#df['idade'] = df['Age']+1
#Manipilar uma coluna que já existe
df['Age'] = df['Age']+1
#df['Age']+=1
df

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%),idade
0,U1000,46,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74,35
1,U1001,36,Germany,Deezer,Country,86,388,Ed Sheeran,Premium,Night,12.06,69.25,25
2,U1002,61,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38,50
3,U1003,67,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51,56
4,U1004,25,Germany,Amazon Music,Reggae,30,328,Adele,Free,Night,30.68,43.41,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,U5995,72,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36,61
4996,U5996,50,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,17.08,58.23,39
4997,U5997,39,Brazil,Amazon Music,Metal,568,277,Taylor Swift,Premium,Night,69.39,51.71,28
4998,U5998,70,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53,59
4999,U5999,42,South Korea,YouTube,Rock,451,145,Adele,Premium,Night,15.45,79.46,31

In [ ]:
#Apagando uma coluna
df.drop('User_ID',axis=1,inplace=True)

In [ ]:
df.drop_duplicates()

,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
0,37,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74
1,27,Germany,Deezer,Country,86,388,Ed Sheeran,Premium,Night,12.06,69.25
2,52,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38
3,58,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51
4,16,Germany,Amazon Music,Reggae,30,328,Adele,Free,Night,30.68,43.41
...,...,...,...,...,...,...,...,...,...,...,...
4995,63,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36
4996,41,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,17.08,58.23
4997,30,Brazil,Amazon Music,Metal,568,277,Taylor Swift,Premium,Night,69.39,51.71
4998,61,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53
4999,33,South Korea,YouTube,Rock,451,145,Adele,Premium,Night,15.45,79.46

In [ ]:
df.sort_values(['Age','Country'], ascending=[True, False],inplace=True)

In [ ]:
df

,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
124,16,USA,Apple Music,Classical,44,193,Billie Eilish,Free,Morning,43.17,79.98
690,16,USA,Deezer,Classical,483,14,Bad Bunny,Premium,Morning,33.94,73.68
691,16,USA,Amazon Music,Metal,189,396,Bad Bunny,Free,Morning,22.46,57.88
885,16,USA,Amazon Music,Reggae,14,15,Post Malone,Free,Afternoon,82.11,57.90
972,16,USA,YouTube,Reggae,454,239,Billie Eilish,Premium,Night,84.48,34.08
...,...,...,...,...,...,...,...,...,...,...,...
3133,63,Australia,Deezer,EDM,32,428,Bad Bunny,Premium,Morning,71.02,42.93
3138,63,Australia,YouTube,Metal,98,314,Ed Sheeran,Free,Afternoon,76.04,76.89
3386,63,Australia,YouTube,Metal,354,459,Dua Lipa,Free,Morning,15.81,30.61
3782,63,Australia,Amazon Music,Jazz,582,187,Post Malone,Premium,Afternoon,12.04,5.34
4284,63,Australia,Spotify,Hip-Hop,215,372,Bad Bunny,Premium,Morning,47.89,67.17

# Alterando o tipo de uma coluna

In [ ]:
dados = {'Gasto': ['1200,50', 3500.75, '950,30']}

In [ ]:
df = pd.DataFrame(dados)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gasto   3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [ ]:
df['Gasto'] = df['Gasto'].astype(str).str.replace(',' , '.').astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gasto   3 non-null      float64
dtypes: float64(1)
memory usage: 156.0 bytes

In [ ]:
df

     Gasto
0  1200.50
1  3500.75
2   950.30

In [ ]:
df.to_csv('sample_data/dados_novos.csv',index=False)

In [ ]:
df.to_excel('sample_data/dados_novos.xlsx',index=False)